### PR TITLE
Nextification

### PR DESCRIPTION
**Pull request by rgbkrk**
I'm switching nteract.io over to [Next.js](https://zeit.co/blog/next) so that I'm more likely to contribute to it while also being able to use our other components.

This is a work in progress as I adapt this. I'm going to hand jam in the built CSS (it's SCSS right now) and then remove that commit later.

Current progress, I've only done the header and footer so far:

screen shot 2017-01-31 at 6 38 28 pm

### CODE REVIEW

**Comment by rgbkrk** [comment]
Alllllmost there...

screen shot 2017-01-31 at 6 52 49 pm

**Comment by philpl** [comment]
@rgbkrk you should test out styled-components some time ;) It's really enjoyable

**Comment by rgbkrk** [comment]
Everybody keeps talking about them. ;) I'll be happy to switch over after we migrate the original base. Want to take over this PR and finish it off?

**Comment by philpl** [comment]
@rgbkrk Not sure whether I'll have time :) I'm actually working on some styled-components contributions myself, besides my other OSS projects ^^

**Comment by rgbkrk** [comment]
Fair enough, I'll keep on going here.

**Comment by rgbkrk** [comment]
Ok, what was missing here was the jQuery code that's run on start. I'd like to see about doing this without jQuery given that we're using React.

```js
$(document).ready(function () {

  function checkHeaderLocation() {
    var top_of_object = $('.page--body').offset().top - 72;
    var top_of_window = $(window).scrollTop();

    return top_of_object < top_of_window;
  }

  function fadeHeaderIn() {
    $(".header--main").addClass("logo-dark");
  }

  function fadeHeaderOut() {
    $(".header--main").removeClass("logo-dark");
  }

  function isContentVisible(element) {
    var bottom_of_object = element.offset().top + element.outerHeight() - 400;
    var bottom_of_window = $(window).scrollTop() + $(window).height();

    return bottom_of_window > bottom_of_object;
  }


  $(window).scroll(function () {

    if (checkHeaderLocation()) {
      fadeHeaderIn();
    } else {
      fadeHeaderOut();
    }

    $('.hidden').each(function (i) {
      if (isContentVisible($(this))) {
        $(this).addClass("animate-content");
      }
    });

  });


  // Init
  setTimeout(function() {
    if (checkHeaderLocation()) {
      fadeHeaderIn();
    } else {
      fadeHeaderOut();
    }

    $('.hidden').each(function (i) {
      if (isContentVisible($(this))) {
        $(this).addClass("animate-content");
      }
    });
  }, 750);

  // Hero
  var scene = $('.hero--scene');
  scene.parallax({
    invertX: false,
    limitY: 0
  });


});

```

**Comment by rgbkrk** [comment]
This now is _roughly_ like the current site. To make the transition to `next.js` work out well though, I'll have to create a build for the `gh-pages` branch.

**Comment by raygesualdo** [comment]
If you are looking to move toward styled-components, I can help with that effort.

**Comment by rgbkrk** [comment]
Folks working in nteract/commuter and nteract/nteract are aiming to go with Aphrodite, that's not holding this PR up though.

**Comment by captainsafia** [comment]
:+1: on Aphrodite. I tried it on a project recently and it was fantastic.

**Comment by raygesualdo** [comment]
Yeah, Aphrodite isn't a bad library. It does have some limitations in that you can't use Aphrodite to write any global CSS; it doesn't support the entire CSS spec, lacking specifically sibling and descendant selectors; and it can be tedious to convert existing CSS (as opposed to starting from scratch) since Aphrodite's CSS is written as a JS object. Within those boundaries, it is a solid CSS-in-JS solution.

**Comment by rgbkrk** [comment]
Ended up bringing the _real_ `next.js` setup into our nteract.io app here: https://github.com/nteract/nteract.io/pull/1

Going ahead and closing this for now.

**Pull request closed without merging**
