### PR TITLE
Gh mergey

### PR DESCRIPTION
**Pull request by rgbkrk**
This is a `git rebase` of `gh-pages` from @aulneau so we can bring it in. This is the `dist` version though, so we'll want to make a specific branch for our source vs. dist and set up automation.

I'm not _actually_ sure if we should merge this yet since we don't have downloads that are fully standalone. Willing to go for it just to push us forward though.

### CODE REVIEW

**Comment by Carreau** [comment]
> I'm not actually sure if we should merge this yet since we don't have downloads that are fully standalone. Willing to go for it just to push us forward though.

Push in on the gh-pages of a separate repo, then you can view it on https://nteract.io/other-repo/ without changing the current page.

**Comment by rgbkrk** [comment]
> Push in on the gh-pages of a separate repo, then you can view it on https://nteract.io/other-repo/ without changing the current page.

That sounds like a good idea. [Current demo is also here](http://nteract.ineffable.co)

**Comment by Carreau** [comment]
time for `./assets/images/nteract_app_demo@2x.png` to pop out when shrinking page is too long.

**Comment by Carreau** [comment]
Issue when refresh the page while and scrolled. The header transition not triggerd. 

screen shot 2016-06-07 at 16 12 28

**Comment by Carreau** [comment]
Also available for other platforms [win][linux]. 

IMHO loogo shoudl be slightly bigger and clickable

**Comment by Carreau** [comment]
1 big missing thing, it's not obvious which language. I would strongly recomand having logo of a few main languages visible.

**Comment by Carreau** [comment]
@captainsafia I'm not sure this was supposed to be merged.

**Comment by rgbkrk** [comment]
Well, it's on @captainsafia and @aulneau to get it in the right state now.

**Comment by captainsafia** [comment]
We iterate on repos with small PRs to fix issues so a single PR doesn't have a ton of commits. This PR accomplishes the task of fixing the git history. The other things can be fixed in separate PRs iteratively.

**Comment by rgbkrk** [comment]
Sounds like I should have targeted it against `gh-pages` instead. It's live now.

**Pull request merged**
